# Generated by Django 5.2.10 on 2026-02-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, help_text='Block A6 Requirement', max_length=100, null=True, verbose_name='品牌'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, help_text='Block A6 Requirement', max_length=100, null=True, verbose_name='材质'),
        ),
    ]
