# Generated by Django 5.2.10 on 2026-02-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_brand_product_material'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatushistory',
            options={'ordering': ['-changed_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, help_text='Optional short video (MP4, WebM)', null=True, upload_to='product_videos/', verbose_name='Product Video'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line1',
            field=models.CharField(max_length=255, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Default Address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='recipient_name',
            field=models.CharField(max_length=100, verbose_name='Recipient Name'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=20, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address_snapshot',
            field=models.TextField(verbose_name='Shipping Address Snapshot'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Hold', 'On Hold'), ('Refunded', 'Refunded')], default='Pending', max_length=20, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name_snapshot',
            field=models.CharField(max_length=200, verbose_name='Product Name Snapshot'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price_snapshot',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price Snapshot'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Changed At'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_html',
            field=models.TextField(help_text='Supports HTML formatting', verbose_name='Description (HTML)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active (On Shelf)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attribute_name',
            field=models.CharField(max_length=50, verbose_name='Attribute Name'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attribute_value',
            field=models.CharField(max_length=100, verbose_name='Attribute Value'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/', verbose_name='Image File'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Is Primary'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Admin', 'Admin/Vendor')], default='Customer', max_length=20, verbose_name='Role'),
        ),
    ]
