# Generated by Django 5.2.10 on 2026-02-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_orderstatushistory_options_product_video_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="origin",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Origin"
            ),
        ),
    ]
